# Generated by Django 5.0.1 on 2024-07-17 07:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Price per kg', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('reorder_trigger', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reorder_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_total', to='inventory.bean')),
            ],
            options={
                'verbose_name': 'Stock Total',
                'verbose_name_plural': 'Stock Totals',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('adj_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'unique_together': {('bean', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('qty_added', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qty_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Entries',
                'unique_together': {('bean', 'date')},
            },
        ),
    ]
