# Generated by Django 5.0.1 on 2024-06-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendbean',
            name='quantity',
        ),
        migrations.AddField(
            model_name='blendbean',
            name='ratio',
            field=models.PositiveIntegerField(default=1, help_text='Ratio in the blend'),
        ),
    ]
