# Generated by Django 5.0.2 on 2024-02-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bean',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bean',
            name='reorder_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='reorder_trigger',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bean',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('qty_added', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qty_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qty_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
            ],
        ),
    ]
