# Generated by Django 5.0.1 on 2024-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_blendbean_quantity_blendbean_ratio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blendbean',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blendbean',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
        migrations.RemoveField(
            model_name='blendbean',
            name='ratio',
        ),
    ]
