# Generated by Django 5.0.2 on 2024-02-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockentry_options_remove_stockentry_qty_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_offset', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_offset', to='inventory.bean')),
            ],
            options={
                'verbose_name': 'Stock Offset',
                'verbose_name_plural': 'Stock Offsets',
            },
        ),
        migrations.DeleteModel(
            name='ManualStockOffset',
        ),
    ]
