# Generated by Django 5.0.1 on 2024-06-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_blendbean_unique_together_blendbean_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='origin',
        ),
    ]
