# Generated by Django 5.0.2 on 2024-02-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockoffset_delete_manualstockoffset'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_total', to='inventory.bean')),
            ],
        ),
    ]
