# Generated by Django 5.0.1 on 2024-06-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_bean_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.blend')),
            ],
        ),
        migrations.DeleteModel(
            name='BlendBean',
        ),
    ]
