# Generated by Django 5.0.2 on 2024-02-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktotal',
            options={'verbose_name': 'Stock Total', 'verbose_name_plural': 'Stock Totals'},
        ),
    ]
