# Generated by Django 5.0.2 on 2024-02-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stocktotal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockoffset',
            name='total_stock_quantity',
        ),
    ]
