# Generated by Django 5.0.1 on 2024-03-04 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockentry_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name': 'Stock Adjustment', 'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('adj_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'unique_together': {('bean', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='StockOffset',
        ),
    ]
