# Generated by Django 5.0.1 on 2024-05-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockentry_options_alter_stockentry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
