# Generated by Django 5.0.1 on 2024-05-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_packaging_product_shipping_alter_bean_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bean')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
