# Generated by Django 5.0.1 on 2024-05-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productbean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='product_label_cost',
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='packaging',
            name='product_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='inventory.productlabel'),
        ),
    ]
