# Generated by Django 5.0.1 on 2024-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_packaging_product_label_cost_productlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
