# Generated by Django 5.0.1 on 2024-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_shipping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbean',
            name='percentage',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
