# Generated by Django 5.0.1 on 2024-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_bean_is_hidden_alter_productbean_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
